### PR TITLE
OSX support and Video Quality menu

### PR DESCRIPTION
**Pull request by dyrnade**
Hello, I made some changes like 

Allowing user to input vlc path. I added this because i wanted to type the path myself :D
Added OSX support.
Added Video Quality choosing menu to the preferences menu and warning about quality to README.

We can discuss about these changes if you wanna add them or not.

Thank you.

### CODE REVIEW

**Comment by kosanmil** [comment]
Hi dyrnade,

Thank you for the additions, they sound great! I will review them by the end of the week, and if everything is OK, I will pull them to the master branch and update the add-on on the official Firefox page.

**Comment by dyrnade** [comment]
Thank you for your interest.

**Comment by kosanmil** [comment]
I have reviewed the pull request. I really like the changes, the feature of quality change is great! I do not have a Mac OS, but I reviewed the code and it seems to be in order.

I would love to pull this to the master branch and make a new version of the addon.

Before I do that, I would like to make a few changes for the Video Quality selection:
- Put the label of the option and the label of the menu items in the locale\options.dtd, so that it is consistent with the other labels.
- Change the label of the menu items to have 'p' at the end (240p, 720p etc.)
- Add an option for "Best Available" (value -1) and 576p (value 576). Want to add those because they are some of the options shown for the --preferred-resolution argument ([as seen here](https://wiki.videolan.org/VLC_command-line_help/)).
- Change the label of the menu to "Preferred Video Quality (needs VLC restart):".

What do you think about these changes?
If you don't mind any of these changes, I can commit them and update the pull request, or you can make the changes if you want to.

**Comment by dyrnade** [comment]
Hi again,
I improved the video quality section according to your suggestions. Now it seems much better.
By the way, i didnt change russian language related options.dtd .
Thanks for suggestions and liking the changes.

**Comment by kosanmil** [comment]
Hi dyrnade,

I have merged the changes to the master branch, and will add the missing labels for the other languages. Afterwards, I will create a new version for the Firefox addon, with the features you implemented.

Thank you for taking an interest in improving this addon, I really appreciate it.

**Comment by dyrnade** [comment]
@kosanmil Thank you for accepting PR. Have a good one.

**Pull request merged**
